apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-orders
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/refresh-timeout: "30s"  # Timeout for refresh operation
spec:
  project: retail-store
  source:
    repoURL: https://github.com/Akashspk13/retail-store-sample-app
    targetRevision: gitops
    path: src/orders/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
